//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int ID { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
    
        public virtual AttachmentLink AttachmentLink { get; set; }
    }
}
