//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTCEmployeeInfo
    {
        public int BTCEmployeeInfoId { get; set; }
        public int BTCEmployeeId { get; set; }
        public long HREmployeeID { get; set; }
    
        public virtual BTCLoginInfo BTCLoginInfo { get; set; }
        public virtual HRW_Employee HRW_Employee { get; set; }
    }
}
