//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeList
    {
        public string EmployeeCode { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
    }
}
