//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRW_VEmpDetailsWithAllEntities
    {
        public string CompanyCode { get; set; }
        public long EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<long> EntityTypeId { get; set; }
        public string EntityType { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string Code { get; set; }
        public string VALUE { get; set; }
        public Nullable<int> EntityGroup { get; set; }
        public string EntityGroupDesc { get; set; }
    }
}
