//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRW_VEmployeeFields
    {
        public bool IsMandatory { get; set; }
        public Nullable<int> CheckDuplicate { get; set; }
        public long ORG_EntityTypeParamID { get; set; }
        public string ParamDescription { get; set; }
        public string DataType { get; set; }
        public Nullable<long> DataTypeEntityID { get; set; }
        public string ParamLinkLevel { get; set; }
        public Nullable<long> EmpEntityParamID { get; set; }
        public Nullable<long> EntityTypeParamID { get; set; }
        public int SortOrder { get; set; }
        public string ParamValue { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string CompanyCode { get; set; }
    }
}
