//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRW_VEmpTypeParamValues
    {
        public Nullable<long> EmployeeID { get; set; }
        public string CompanyCode { get; set; }
        public long EntityTypeParamID { get; set; }
        public string Description { get; set; }
        public string ParamValue { get; set; }
    }
}
