//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPO
    {
        public int ID { get; set; }
        public string LPONo { get; set; }
        public Nullable<int> RFQID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsAT { get; set; }
        public Nullable<bool> IsHS { get; set; }
        public Nullable<bool> IsPC { get; set; }
    
        public virtual RFQ RFQ { get; set; }
        public virtual Quotation Quotation { get; set; }
    }
}
