//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPO
    {
        public int LPOID { get; set; }
        public string LPONo { get; set; }
        public int RFQID { get; set; }
        public int QuotationID { get; set; }
        public int ATQuotationID { get; set; }
        public int HSQuotationID { get; set; }
        public int PCQuotationID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ATQuotation ATQuotation { get; set; }
        public virtual HSQuotation HSQuotation { get; set; }
        public virtual PCQuotation PCQuotation { get; set; }
        public virtual Quotation Quotation { get; set; }
        public virtual RFQ RFQ { get; set; }
    }
}
