//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQ()
        {
            this.LPOes = new HashSet<LPO>();
        }
    
        public int RFQID { get; set; }
        public int TravelAgencyID { get; set; }
        public int TravelRequestID { get; set; }
        public int UserID { get; set; }
        public string Remarks { get; set; }
        public int Processing { get; set; }
        public int ProcessingSection { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LPO> LPOes { get; set; }
        public virtual TravelAgency TravelAgency { get; set; }
        public virtual TravelRequest TravelRequest { get; set; }
        public virtual User User { get; set; }
    }
}
