//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelRequest()
        {
            this.TravelRequestDetails = new HashSet<TravelRequestDetail>();
        }
    
        public int TravelRequestID { get; set; }
        public int BTCEmployeeId { get; set; }
        public string ApplicationNumber { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ReutrnDate { get; set; }
        public Nullable<System.DateTime> FirstBusinessDay { get; set; }
        public Nullable<System.DateTime> LastBusinessDay { get; set; }
        public string Remarks { get; set; }
        public string AirTicketManagement { get; set; }
        public string HotelName { get; set; }
        public string TravelAllowance { get; set; }
        public string HotelStay { get; set; }
        public string HotelCategory { get; set; }
        public string RoomCategory { get; set; }
        public string RoomType { get; set; }
        public string AdditionalAllowance { get; set; }
        public string AirportPickUp { get; set; }
        public string PickUpBy { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public int ApprovalLevel { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string ApprovalRemarks { get; set; }
    
        public virtual BTCLoginInfo BTCLoginInfo { get; set; }
        public virtual BTCLoginInfo BTCLoginInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelRequestDetail> TravelRequestDetails { get; set; }
    }
}
