//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRequestDetail
    {
        public int TravelRequestDetailsID { get; set; }
        public int TravelRequestID { get; set; }
        public int OriginPort { get; set; }
        public int DestinationPort { get; set; }
        public string TicketClass { get; set; }
        public Nullable<int> DailyAllowance { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> TravelDays { get; set; }
        public string Remarks { get; set; }
        public string PurposeOfVisit { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual TravelRequest TravelRequest { get; set; }
    }
}
