//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Request_System_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Cust_Code { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_City { get; set; }
        public string Working_Area { get; set; }
        public string Cust_Country { get; set; }
        public Nullable<int> Grade { get; set; }
        public decimal Opening_Amt { get; set; }
        public decimal Receive_Amt { get; set; }
        public decimal Payment_Amt { get; set; }
        public decimal Outstanding_Amt { get; set; }
        public string Phone_No { get; set; }
        public string Agent_Code { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
